spring:
  datasource:
    url: jdbc:mysql://localhost:3306/integrador?useSSL=false
    password: NoControl3232
    username: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        ddl:
#          auto: update